openapi: 3.0.0
info:
  version: 1.0.0
  title: Clarke Energia API Fornecedores
  description: API for managing suppliers

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MVRFULLSTACKDEV/Clarke-api/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:3000
  - description: Link Render
    url: https://desafio-clarke-energia-backend-3ueh.vercel.app/
paths:
  /supplier:
    post:
      summary: Create a new supplier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplieCreationProps'
      responses:
        '201':
          description: Successfully created a new supplier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplieProps'
        '400':
          description: Invalid parameters provided

  /supplier/{id}/find:
    get:
      summary: Get a supplier by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the supplier
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved a supplier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplieProps'
        '404':
          description: Supplier not found
          
  /supplier/find:
    get:
      summary: Get all supplier
      responses:
        '200':
          description: Successfully retrieved all suppliers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupplieProps'
        '404':
          description: No suppliers found        

  /supplier/{id}/edit:
    put:
      summary: Update a supplier by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the supplier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplieCreationProps'
      responses:
        '200':
          description: Successfully updated a supplier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplieProps'
        '400':
          description: Invalid parameters provided
        '404':
          description: Supplier not found
  /supplier/{id}/delete:
    delete:
      summary: Delete a supplier by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the supplier
          schema:
            type: string
      responses:
        '204':
          description: Supplier successfully deleted
        '404':
          description: Supplier not found

components:
  schemas:
    SupplieCreationProps:
      type: object
      properties:
        name:
          type: string
        logo:
          type: string
        stateAbbreviation:
          type: string
        costPerKwh:
          type: number
        minKwhLimit:
          type: number
        totalCustomers:
          type: number
        averageCustomerRating:
          type: number

    SupplieProps:
      allOf:
        - $ref: '#/components/schemas/SupplieCreationProps'
        - type: object
          properties:
            id:
              type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time